---
# tasks file for wdijkerman.zabbix

- name: "Include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Set short version name"
  set_fact:
      zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"
  tags:
    - always

- name: "Get Apache version"
  action: shell apachectl -v | grep 'version' | awk -F '/' '{ print $2 }'| awk '{ print $1 }' | cut -c 1-3
  changed_when: apachectl_version.rc == 7
  register: apachectl_version
  always_run: yes
  tags:
    - zabbix-server
    - apache

- name: "Set correct apache_version"
  set_fact:
    apache_version: "{{ apachectl_version.stdout }}"
  tags:
    - zabbix-server
    - apache

- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"
  tags:
    - always

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - always

- name: "Installing the postgresql database"
  include: "postgresql.yml"
  when: database_type_long == "postgresql"
  tags:
    - always

- name: "Installing the mysql database"
  include: "mysql.yml"
  when: database_type_long == "mysql"
  tags:
    - always

- name: "Configure zabbix-server"
  template: src=zabbix_server.conf.j2
            dest=/etc/zabbix/zabbix_server.conf
            owner=zabbix
            group=zabbix
            mode=0644
  notify: zabbix-server restarted
  tags:
    - zabbix-server
    - init
    - config

- name: "Create include dir zabbix-server"
  file: path={{ server_include }}
        owner=zabbix
        group=zabbix
        state=directory
        mode=0644
  tags:
    - zabbix-server
    - init
    - config

- name: "Create zabbix-web directory"
  file: path=/etc/zabbix/web
        owner={{ apache_user }}
        group={{ apache_group }}
        state=directory
        mode=0755
  tags:
    - zabbix-server
    - init
    - config

- name: "Configure zabbix-web"
  template: src=zabbix.conf.php.j2
            dest=/etc/zabbix/web/zabbix.conf.php
            owner={{ apache_user }}
            group={{ apache_group }}
            mode=0644
  tags:
    - zabbix-server
    - init
    - config
